import {
  SunIcon,
  MoonIcon,
  ArrowLeftIcon,
  AvatarIcon,
  BookmarkIcon,
  ChatBubbleIcon,
  PlusIcon,
  MagnifyingGlassIcon,
  PaperPlaneIcon,
  ImageIcon,
  Link2Icon,
  ChevronDownIcon,
  StarFilledIcon,
  StarIcon,
  UpdateIcon,
  CrossCircledIcon,
  CheckIcon,
  Cross1Icon,
  ChevronLeftIcon,
} from "@radix-ui/react-icons";

export const Icons = {
  sun: SunIcon,
  moon: MoonIcon,
  avatar: AvatarIcon,
  saved: BookmarkIcon,
  chaticon: ChatBubbleIcon,
  add: PlusIcon,
  replyIcon: ChevronDownIcon,
  search: MagnifyingGlassIcon,
  moveback: ChevronLeftIcon,
  sendIcon: PaperPlaneIcon,
  fileLink: Link2Icon,
  image: ImageIcon,
  remove: CrossCircledIcon,
  yes: CheckIcon,
  no: Cross1Icon,
  new: StarFilledIcon,
  likeNew: StarIcon,
  used: UpdateIcon,
  buffering: UpdateIcon,
};
