import type { Metadata } from "next";
import { inter } from "@/app/ui/fonts";
import "@/app/globals.css";
import Navbar from "@/app/ui/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="min-h-screen">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
};
export default RootLayout;
